runtime: python27
api_version: 1
threadsafe: true

handlers:

- url: /static
  static_dir: static

- url: /.*
  script: giftwiz_project.wsgi.application

libraries:

- name: django
  version: "latest"

- name: MySQLdb
  version: "latest"

env_variables:
    DJANGO_SETTINGS_MODULE: 'giftwiz_project.settings'
    CLOUDSQL_CONNECTION_NAME: mythic-plexus-194517:europe-west1:giftwiz-api
    CLOUDSQL_USER: jamesdix
    CLOUDSQL_PASSWORD: giftwiz


skip_files:
- ^(.*/)?#.*#$
- ^(.*/)?.*~$
- ^(.*/)?.*\.py[co]$
- ^(.*/)?.*/RCS/.*$
- ^(.*/)?\..*$
- ^env/.*$
- ^downloaded_feeds/*
- ^db.sqlite
