# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-01-22 21:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_product_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='url',
            field=models.CharField(max_length=1000),
        ),
    ]
