# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-02-18 02:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20180218_0229'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='url',
            field=models.CharField(default='', max_length=1000),
            preserve_default=False,
        ),
    ]
